name: Checks
on: [push, pull_request]
jobs:
  installation_and_download:
    name: Installation / Download
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[SKIP-CI]')"
    steps:
      - uses: actions/checkout@v1
      - name: 'Install gdindex-downloader'
        run: 'bash install.sh -b ${GITHUB_REF##*/}'
      - name: 'Download Files'
        run: 'bash test.sh'
