name: Checks
on:
  push:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[SKIP-CI]')"
    steps:
      -
        uses: actions/checkout@v1
      -
        name: 'Bash it !'
        run: 'sudo apt-get -y install snapd && sudo snap install shfmt && bash'
      -
        name: 'Here we go'
        run: 'bash test'
